inherit: true

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.4
    analysis:
        environment:
            php:
                version: 7.4

filter:
  paths:
    - 'src/*'
  excluded_paths:
    - tests/*

before_commands:
  - 'composer install --no-interaction --no-scripts'

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
